// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLnrdSWdNU_ssBP0cf_4R1Ss7Mke-b83c',
    appId: '1:884287479378:web:9ae79ab888dac7c8b2098b',
    messagingSenderId: '884287479378',
    projectId: 'train-ticket-d08b1',
    authDomain: 'train-ticket-d08b1.firebaseapp.com',
    storageBucket: 'train-ticket-d08b1.firebasestorage.app',
    measurementId: 'G-B2ML268K1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbepNtGuX_Ji_KG0HioTCRoI1JLhYs_PQ',
    appId: '1:884287479378:android:1908d4ea22951994b2098b',
    messagingSenderId: '884287479378',
    projectId: 'train-ticket-d08b1',
    storageBucket: 'train-ticket-d08b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdNFzMmL-izXYErepc-_MY_vOyUjMu1vo',
    appId: '1:884287479378:ios:c642c265c7ba9a43b2098b',
    messagingSenderId: '884287479378',
    projectId: 'train-ticket-d08b1',
    storageBucket: 'train-ticket-d08b1.firebasestorage.app',
    iosBundleId: 'com.example.railTicketing',
  );
}
